version: '2.2'
services:
 mysql:
  restart: unless-stopped
  image: mariadb:10.1.30
  env_file: .env
  environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
   - MYSQL_USER=${MYSQL_USER}
   - MYSQL_PASSWORD=${MYSQL_PASS}
   - TZ=America/Sao_Paulo
  ports:
   - ${MYSQL_PORT}:3306

 myadmin:
  mem_limit: 128m
  memswap_limit: 0
  mem_swappiness: 0
  restart: unless-stopped
  image: phpmyadmin/phpmyadmin
  env_file: .env
  environment:
   - PMA_USER=${MYSQL_USER}
   - PMA_PASSWORD=${MYSQL_PASS}
   - PMA_ARBITRARY=1
  ports:
   - ${MYADMIN_PORT}:80
  links:
   - mysql:db
  depends_on: 
    - mysql